name: Fetch SQLiteCloud Scription Table

on:
  workflow_dispatch:
  schedule:
    - cron: "5 */5 * * *"  # 每5小時5分鐘

jobs:
  fetch-food:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 24
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Install Dependencies
        run: npm install @sqlitecloud/drivers

      - name: Query SQLiteCloud scription table
        env:
          SQLITECLOUD_URL: ${{ secrets.SQLITECLOUD_URL }}
        run: node fetch-scription.js

      - name: Upload Result
        uses: actions/upload-artifact@v6
        with:
          name: scription-json
          path: scription.json

      - name: Print scription.json
        run: cat scription.json
